### ISSUE TITLE
Please fix the workflow of sending messages.

### ISSUE THREAD

**Issue by sairam4123** [3ddelano/discord.gd#1]
Hi. I'm Sairam and I'm a user of discord.gd, I'm working on a bot that needs to send messages every x hours, daily. 

The problem is that the workflow defined in this library don't support sending messages. 

It'd be cool if we can send the messages without having to wait for another person to send a message which is the current workflow in this library.

So things that might need changes:
1. Changing the discord.gd's send "message: Message" parameter to a new class that doesn't need author or other data. Except the data that we need to pass to Discord to send the message.

**Comment by INdIEDeV016** [comment]
Hi, I am INdIE DeV. To improve and aid on the suggestion provided by @sairam4123, I would like to suggest that the sending/replying/editting/deleting of messages be done from the `Channel` Class itself and the content parameter should be a JSON/payload for Discord that will be sent using the aforementioned functions.

The below image is an example implementation from my side...
![image](https://user-images.githubusercontent.com/80198819/132080209-30a6e270-980c-41cd-a64a-816d7157848a.png)

**Comment by 3ddelano** [comment]
Thanks! I will look into it. It might be a overhaul since, but we can add this in the next major release. If possible can you make a pull request with some code, since I will not be able to work on this for a few weeks till my university exams ends. Cheers. If you want you can join the Discord server where other developers are also there.

**Comment by 3ddelano** [comment]
In theory I wanted it it to be like:
var msg = channel.send('Message text and other options', {files, embeds, components})
msg.edit('new message')
msg.delete()
But I wasn't able to figure it out.

**Comment by sairam4123** [comment]
Well.. that should be pretty easy if you can work out the init of the message. I'd recommend giving discord.py's implementation a look.

**Comment by 3ddelano** [comment]
Updated the bot.send method to accept the Message or a channel_id. Will close this for now.
