### ISSUE TITLE
Godot 4.0 support?

### ISSUE THREAD

**Issue by TicklesTheBrain** [3ddelano/discord.gd#17]
Hey, great repo. Is this currently compatible with Godot 4.0? If not, do you plan to update with 4.0 support?

Thanks.

**Comment by 3ddelano** [comment]
Current I have no plans for that, since I'm developing v2 of the plugin still for Godot 3. For now there is a port of the plugin for Godot 4 available here [Discord.gd Godot4](https://github.com/INdIEDeV016/discord.gd)

**Comment by 3ddelano** [comment]
Another alternative is [Cordot](https://github.com/Abdera7mane/cordot/tree/godot_4.0)

**Comment by 3ddelano** [comment]
Another alternative is to open the project in Godot 4. The editor should auto convert most of the code to work in Godot 4. A little manual change may be needed.
