### ISSUE TITLE
Logging into user account

### ISSUE THREAD

**Issue by ITZProGamerDieYT** [3ddelano/discord.gd#2]
add the ability to authenticate with a user account

**Comment by ITZProGamerDieYT** [comment]
note: not for self-bot use

**Comment by ITZProGamerDieYT** [comment]
nvm

**Comment by 3ddelano** [comment]
I think login with token should work the same, although I would not recommend it since its against Discord's TOS.

**Comment by ITZProGamerDieYT** [comment]
It didn't work + it uses undocumented apis
