### ISSUE TITLE
The contents of a message are null until i call the bot with @BotName

### ISSUE THREAD

**Issue by HashirShazad** [3ddelano/discord.gd#21]

**Comment by 3ddelano** [comment]
@HashirShazad this is a configuration issue with the Discord API. In a recent update the message.content has become a privileged intent. To enable it goto the discord developer portal -> your application -> Bot -> in the privileged intents enable the message content intent.

**Comment by HashirShazad** [comment]
Thanks for your email, i will try the solution you have listed, I am really
grateful to you.

**Comment by HashirShazad** [comment]
This worked
