### ISSUE TITLE
I cant get the email of the author of the message

### ISSUE THREAD

**Issue by HashirShazad** [3ddelano/discord.gd#22]
`print(msg.author.email)`
Returns:
Nothing
It is an empty string I think for some reason

**Comment by 3ddelano** [comment]
Discord doesn't give email of the users in the message payload. You can use the `msg.author.id` as a unique identifier for a user.

**Comment by HashirShazad** [comment]
I need the email of the user rather than an identifier.

**Comment by 3ddelano** [comment]
For that you have to use  [Discord Oauth2](https://discord.com/developers/docs/topics/oauth2), with this you can get the user personal information like email by giving the `email` scope. Though this plugin does not support this.

**Comment by HashirShazad** [comment]
Oh no, i enable email at Oauth2 but now it gives a link to me:
https://discord.com/oauth2/authorize?client_id=1224374449084567755&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1&scope=email
so is there any way I can get the users email through gdscript?

**Comment by 3ddelano** [comment]
Check this out [Oauth 2 in Godot](https://youtu.be/07xfNmyJ9Nw)
