### ISSUE TITLE
Can't set up a simple bot

### ISSUE THREAD

**Issue by wolfsmith520-github** [3ddelano/discord.gd#24]
Followed the tutorial and run the bot, this error happened
https://youtu.be/kZgDXLUJEjw?si=S96G4Hn9xWiIPZYN

E 0:00:00.834   _do_handshake: TLS handshake error: -9984
  <C++ Source>  modules/mbedtls/stream_peer_mbedtls.cpp:87 @ _do_handshake()
  <Stack Trace> discord.gd:477 @ _process()

btw, is this plugin still working after discord changed their api

**Comment by 3ddelano** [comment]
I just tried my bot and its running fine.

What is your Godot version?
What are the steps to reproduce your error?

**Comment by 3ddelano** [comment]
You can try whats mentioned in #11

**Comment by wolfsmith520-github** [comment]
![Code](https://github.com/3ddelano/discord.gd/assets/67470569/984e6b52-af94-402c-ba2c-8120bd3336ef)
![Settings](https://github.com/3ddelano/discord.gd/assets/67470569/77b62210-0e8d-48a9-9feb-c18ebaf88124)
Here is my set up, seems not working, my Version is 3.5.3

**Comment by 3ddelano** [comment]
Is your bot token correct?

**Comment by wolfsmith520-github** [comment]
> Is your bot token correct?

![image](https://github.com/3ddelano/discord.gd/assets/67470569/48b9d3e1-8922-4266-8886-1a0d88aa15c1)
If this is the reset token button after the update then yes

**Comment by 3ddelano** [comment]
Can you try running the project in Godot 3.4.x

**Comment by wolfsmith520-github** [comment]
> Can you try running the project in Godot 3.4.x

Oh, I may know the issue, I am actually Chinese, and discord is blocked by the Fire Wall, I think I may have trouble connecting Discord's Developer Network. Thanks for your help anyway
