### ISSUE TITLE
Errors when sending MessageActionRow + MessageButton

### ISSUE THREAD

**Issue by nekotogd** [3ddelano/discord.gd#3]
## Version info

discord.gd v1.1.3

From releases, I have **not cloned** the master branch

## Issue

The Documentation suggests using this code to create and send a button:

```gdscript
var button = MessageButton.new().set_style(MessageButton.STYLES.DEFAULT).set_label("A")
button.set_custom_id("primary_custom")
var row = MessageActionRow.new().add_component(button)
yield(bot.send(message, {
"components": [row]
}))
```

However this gives me 2 errors:

### `expected "," after the first argument of yield`

So I removed the yield and just used 
```gdscript
bot.send(message, {"components":[row]})
```

But this gives me another error:

### `Assertion failed: Error sending request. See output window`

The code it brings me to in the editor is the following:

```gdscript
if method != HTTPClient.METHOD_DELETE:
  assert(not response.has('code'), 'Error sending request. See output window')
```

**Comment by 3ddelano** [comment]
Make sure the bot has the necessary permissions to like SEND_MESSAGES. To do this you can use,
`GDScript
var perms = bot.permissions_in(message.channel_id)
if not perms.has("SEND_MESSAGES"):
    return

bot.send(message, "I can send messages")
`
For more info check out this youtube video: https://youtu.be/BGXsxpGYgLQ

**Comment by 3ddelano** [comment]
Thanks for reporting there is a typo in the docs I will update it.

**Comment by nekotogd** [comment]
### It worked!

Adding a content to the button fixed the issue!

**Would like to request for this to be added to the documentation to avoid confusion.**

Just to specify that the message must have some content in it to send.

**Comment by 3ddelano** [comment]
Docs are updated. More common errors will be added to the docs soon. Closing since issue is resolved.
