### ISSUE TITLE
Suggestion: Slash Commands Support

### ISSUE THREAD

**Issue by nekotogd** [3ddelano/discord.gd#6]
Would really love to be able to make slash commands with `discord.gd`!

From reading the documentation it seems like its just sending a dictionary?
[https://discord.com/developers/docs/interactions/application-commands](url)

I'm not sure exactly since I've never done HTTP requests before, but I would really love to see this feature in a future release!

**Comment by 3ddelano** [comment]
Sure I will try to add menu component and slash cmds soon.

**Comment by 3ddelano** [comment]
Slash commands now available from Release 1.1.9

**Comment by nekotogd** [comment]
Brilliant! Thanks so much!
