### ISSUE TITLE
Mistake in Getting Started 

### ISSUE THREAD

**Issue by WordsetterFak** [3ddelano/discord.gd#7]
In the getting started code snippet, which sets up a basic bot, there is a + missing, in the second print statement of the _on_DiscordBot_bot_ready method,between the bot.guilds.size() and 'guilds'.

`print('Listening on ' + str(bot.channels.size()) + ' channels and ' + str(bot.guilds.size()) ' guilds.')`

**Comment by 3ddelano** [comment]
Thanks for the report. Its been modified. [commit](https://github.com/3ddelano/discord.gd/commit/fc9f3d94bf91f5c57815ebc3fd1cb69f745c7f35)
