### ISSUE TITLE
Issue with loading large servers

### ISSUE THREAD

**Issue by HansKillinger** [3ddelano/discord.gd#8]
I am currently having issues when attempting to connect to larger servers. I believe it has something to do with the websocket getting bogged down. My program works fine on other small testing servers great, but moment it is invited into main server environment with 4k users, it locks up and does not fully login. It will still attempt to send heartbeats, but they do not appear to go through, as the bot will get logged off shortly after sending, and no "ack" gets returned. During all this, no signals are generated beyond the initial connection being accepted.

**Comment by 3ddelano** [comment]
Not really sure how this could be fixed. But I'll ask on the Godot server.

**Comment by 3ddelano** [comment]
In ProjectSetting -> Network -> Limits, you can increase the values in the "Websocket Client" Section, specifically the "Max In buffer Kb" and "Max In Packets"
![image](https://user-images.githubusercontent.com/24526102/149700381-9b304e5f-317f-4640-91e2-6ba9257e13c8.png)
